config:
  default: true
  MD013: false
  MD024: false
  MD026: false
  MD007:
    indent: 4
  MD046: false
  MD033: false
  MD034: false
  MD040: false
  MD025: false
  MD029: false
ignores:
  - node_modules
  - CHANGELOG.md
  - README.md
