site_name: かめぱわぁ～るどドキュメント
site_url: https://kamesuta.com/docs/
site_description: >-
  ようこそ！かめぱわぁ～るどのパブリックドキュメントへ
theme:
  name: material
  custom_dir: overrides
  language: ja
  icon:
    logo: material/book-open-variant
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
  font:
    text: BIZ UDPGothic
    code: BIZ UDGothic
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate

plugins:
  - social:
      cards_font: Noto Sans JP
  - search:
      lang:
        - ja
        - en

extra:
  social:
    - icon: fontawesome/solid/house-chimney
      link: https://www.kamesuta.com
      name: かめぱわぁ～るど Webサイト
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kamepower
      name: かめぱわぁ～るど Discord
    - icon: fontawesome/brands/github
      link: https://github.com/KamePowerWorld
      name: かめぱわぁ～るど GitHub
  generator: false

copyright: '"Minecraft" is a trademark of Mojang Synergies AB<br>© かめぱわぁ～るど / Made with Material for MkDocs'

repo_name: www.kamesuta.com
repo_url: https://github.com/KamePowerWorld/www.kamesuta.com

edit_uri: edit/v1.1/apps/mkdocs/docs

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - extra/index.js

extra_css:
  - extra/index.css
